-- Add migration script here

CREATE TABLE User (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  roleId INTEGER NOT NULL,
  fullName TEXT,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (roleId) REFERENCES Role(id)
);
