-- Add migration script here

CREATE TABLE User (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  role_id INTEGER NOT NULL,
  full_name TEXT,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (role_id) REFERENCES Role(id)
);
